package api

import "errors"

var (
	ErrORDER_ALWAYS_DECLINED = errors.New("Заказ уже расформирован")
	ErrALL_SHIPMENTS_SENT = errors.New("Все отправления уже отправлены")
	ErrBARCODE_ERROR = errors.New("Ошибка при получении ШПИ")
	ErrEMPTY_ADDRESS_TYPE_TO = errors.New("Тип адреса не указан")
	ErrEMPTY_INDEX_TO = errors.New("Почтовый индекс не указан")
	ErrEMPTY_INSR_VALUE = errors.New("Объявленная сумма не указана")
	ErrEMPTY_MAIL_CATEGORY = errors.New("Категория почтового отправления не указана")
	ErrEMPTY_MAIL_DIRECT = errors.New("Почтовое направление не указано")
	ErrEMPTY_MAIL_TYPE = errors.New("Тип почтового отправления не указан")
	ErrEMPTY_MASS = errors.New("Масса не указана")
	ErrEMPTY_NUM_ADDRESS_TYPE = errors.New("Не задан номер для соответствующего типа адреса")
	ErrEMPTY_PAYMENT = errors.New("Наложенный платеж не указан")
	ErrEMPTY_PLACE_TO = errors.New("Населенный пункт не указан")
	ErrEMPTY_REGION_TO = errors.New("Регион не заполнен")
	ErrEMPTY_TRANSPORT_TYPE = errors.New("Способ пересылки не указан")
	ErrEMPTY_POSTOFFICE_CODE = errors.New("Индекс приемного почтового отделения не задан")
	ErrILLEGAL_ADDRESS_TYPE_TO = errors.New("Тип адреса некорректен")
	ErrILLEGAL_INDEX_TO = errors.New("Почтовый индекс некорректен")
	ErrILLEGAL_INITIALS = errors.New("ФИО некорректно")
	ErrILLEGAL_INSR_VALUE = errors.New("Объявленная сумма некорректна")
	ErrILLEGAL_MAIL_CATEGORY = errors.New("Категория почтового отправления некорректна")
	ErrILLEGAL_MAIL_DIRECT = errors.New("Почтовое направление некорректно")
	ErrILLEGAL_MAIL_TYPE = errors.New("Тип почтового отправления некорректен")
	ErrILLEGAL_MASS = errors.New("Масса некорректна")
	ErrILLEGAL_MASS_EXCESS = errors.New("Вес отправления не должен превышать N кг")
	ErrILLEGAL_PAYMENT = errors.New("Наложенный платеж некорректен")
	ErrILLEGAL_POSTCODE = errors.New("Индекс приемного почтового отделения в настройках и в партии отличаются")
	ErrILLEGAL_POSTOFFICE_CODE = errors.New("Индекс приемного почтового отделения некорректен")
	ErrILLEGAL_TRANSPORT_TYPE = errors.New("Некорректный способ пересылки")
	ErrIMP13N_ERROR = errors.New("Ошибка имперсонализации")
	ErrINSR_VALUE_EXCEEDS_MAX = errors.New("Превышено максимальное значение N руб")
	ErrNO_AVAILABLE_POSTOFFICES = errors.New("Нет доступных точек сдачи")
	ErrNOT_FOUND = errors.New("Отправление не найдено")
	ErrPAST_DUE_DATE = errors.New("Дата отправки просрочена")
	ErrREADONLY_STATE = errors.New("Изменения в партии недопустимы")
	ErrRESTRICTED_MAIL_CATEGORY = errors.New("Для создания отправлений с наложенным платежом необходимо указать номер ЕСПП в настройках сервиса. Обратитесь к вашему персональному менеджеру в Почте или напишите письмо на почтовый ящик support.otpravka@russianpost.ru")
	ErrSENDING_MAIL_FAILED = errors.New("Ошибка при отправке почты")
	ErrTARIFF_ERROR = errors.New("Ошибка при расчете тарифа")
	ErrDIFFERENT_TRANSPORT_TYPE = errors.New("Способы пересылки отправления и партии отличаются")
	ErrDIFFERENT_MAIL_TYPE = errors.New("Типы почтовых отправлений не совпадают")
	ErrDIFFERENT_MAIL_CATEGORY = errors.New("Категории почтовых отправления не совпадают")
	ErrDIFFERENT_MAIL_RANK = errors.New("Разряд отправления и партии отличаются")
	ErrABSENT_OVERSIZE_POSTMARK = errors.New("Отправление не может быть добавлено в партию с отметкой \"Негабаритная\"")
	ErrUNEXPECTED_OVERSIZE_POSTMARK = errors.New("Негабаритное отправление не может быть добавлено в партию без отметки \"Негабаритная\"")
	ErrABSENT_FRAGILE_POSTMARK = errors.New("Отправление без отметки \"Осторожно/Хрупкое\" не может быть добавлено в партию с отметкой \"Осторожно/Хрупкое\"")
	ErrUNEXPECTED_FRAGILE_POSTMARK = errors.New("Отправление с отметкой \"Осторожно/Хрупкое\" не может быть добавлено в партию без отметки \"Осторожно/Хрупкое\"")
	ErrABSENT_COURIER_DELIVERY_POSTMARK = errors.New("Отправление без отметки \"Курьер\" не может быть добавлено в партию с отметкой \"Курьер\"")
	ErrUNEXPECTED_COURIER_DELIVERY_POSTMARK = errors.New("Отправление с отметкой \"Курьер\" не может быть добавлено в партию без отметки \"Курьер\"")
	ErrABSENT_ORDER_OF_NOTICE_POSTMARK = errors.New("Отправление без отметки \"С заказным уведомлением\" не может быть добавлено в партию с отметкой \"С заказным уведомлением\"")
	ErrUNEXPECTED_ORDER_OF_NOTICE_POSTMARK = errors.New("Отправление с отметкой \"С заказным уведомлением\" не может быть добавлено в партию без отметки \"С заказным уведомлением\"")
	ErrABSENT_SIMPLE_NOTICE_POSTMARK = errors.New("Отправление без отметки \"С простым уведомлением\" не может быть добавлено в партию с отметкой \"С простым уведомлением\"")
	ErrUNEXPECTED_SIMPLE_NOTICE_POSTMARK = errors.New("Отправление с отметкой \"С простым уведомлением\" не может быть добавлено в партию без отметки \"С простым уведомлением\"")
	ErrUNDEFINED = errors.New("Неопределенная ошибка")
)
